[dltos]
image=fedora-toolbox:latest
entry=true
nvidia=true
volume=/usr/share/dltos:/usr/share/dltos
pre_init_hooks=/usr/share/dltos/pre-init.sh
init_hooks=/usr/share/dltos/init.sh

# --- languages ---
additional_packages=nodejs-npm shfmt ShellCheck

# --- shell ---
additional_packages=starship chezmoi direnv keychain fastfetch
additional_packages=zoxide bat ripgrep fd-find eza btop nvtop

# --- dev ---
additional_packages=git just cloc pre-commit git-delta lazygit helix mold
