[dltos]
image=fedora-toolbox:latest
entry=true
nvidia=true
volume=/usr/share/dltos:/usr/share/dltos
pre_init_hooks=export SHELL=/bin/fish
pre_init_hooks=/usr/share/dltos/pre-init.sh
init_hooks=/usr/share/dltos/init.sh

# --- languages ---
additional_packages=golang delve gopls golangci-lint cargo uv python3-devel nodejs-npm shfmt ShellCheck

# --- shell ---
additional_packages=fish starship chezmoi direnv keychain fastfetch
additional_packages=zoxide bat ripgrep fd-find eza btop nvtop

# --- network ---
additional_packages=nc nmap rclone

# --- dev ---
additional_packages=git just pre-commit cloc git-delta lazygit helix mold cargo-watch

# --- containers ---
additional_packages=docker-cli docker-compose-switch
volume=/run/user/1000/podman/podman.sock:/var/run/docker.sock

# --- data ---
additional_packages=jq yq