[dltos]
image=fedora-toolbox:latest
entry=true
nvidia=true
volume=/usr/share/dltos:/usr/share/dltos
pre_init_hooks=export SHELL=/bin/fish
pre_init_hooks=/usr/share/dltos/pre-init.sh
init_hooks=/usr/share/dltos/init.sh

# --- languages ---
additional_packages=golang delve gopls golangci-lint cargo uv python3-devel nodejs-npm shfmt ShellCheck

# --- shell ---
additional_packages=fish starship chezmoi direnv keychain fastfetch
additional_packages=zoxide bat ripgrep fd-find eza ncdu age btop nvtop lshw lspci

# --- network ---
additional_packages=iperf3 mkcert nc nmap ipcalc prettyping rclone

# --- graphics ---
additional_packages=ImageMagick ImageMagick-heic libheif-freeworld libde265

# --- dev ---
additional_packages=git just pre-commit cloc git-delta lazygit helix

# --- containers ---
additional_packages=docker-cli docker-compose-switch
volume=/run/user/1000/podman/podman.sock:/var/run/docker.sock

# --- ai ---
# init.sh only

# --- data ---
additional_packages=jq yq sqlite3 miller gnuplot
